### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Chiharu-Hagihara** [Chiharu-Hagihara/Man10Market#1]
1.16対応

DONE✅

**Comment by Chiharu-Hagihara** [comment]
1.16対応完了

エラー修正
[14:13:28 ERROR]: Error occurred while enabling Man10Market v1.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
        at red.man10.man10market.mapp.MappRenderer.listFolder(MappRenderer.java:1032) ~[?:?]
        at red.man10.man10market.mapp.MappRenderer.loadImages(MappRenderer.java:1070) ~[?:?]
        at red.man10.man10market.mapp.MappRenderer.setup(MappRenderer.java:685) ~[?:?]
        at red.man10.man10market.MarketPlugin.onEnable(MarketPlugin.kt:696) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-185]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-185]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-185]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-185]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-185]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by Chiharu-Hagihara** [comment]
[15:10:43 INFO]: [Man10Market] Enabling Man10Market v1.0-SNAPSHOT
[15:10:43 INFO]: MarketCommand () ->
[15:10:43 INFO]: MarketCommand
[15:10:43 INFO]: [Man10Market] Config loaded  45.8.223.54 / MEC11
[15:10:44 ERROR]: Could not connect to MySQL server, error message: Public Key Retrieval is not allowed
[15:10:44 INFO]: failed to open MYSQL
[15:10:44 INFO]: [Man10Market] Unable to establish a MySQL connection.
[15:10:44 INFO]: [Man10Market] Config loaded  45.8.223.54 / MEC11
[15:10:45 ERROR]: Could not connect to MySQL server, error message: Public Key Retrieval is not allowed
[15:10:45 INFO]: failed to open MYSQL
[15:10:45 INFO]: [Man10Market] Unable to establish a MySQL connection.
[15:10:45 INFO]: [Man10Market] Config loaded  45.8.223.54 / MEC11
[15:10:45 ERROR]: Could not connect to MySQL server, error message: Public Key Retrieval is not allowed
[15:10:45 INFO]: failed to open MYSQL
[15:10:45 INFO]: [Man10Market] Unable to establish a MySQL connection.
[15:10:45 INFO]: BalanceCommand
[15:10:45 INFO]:  PayItemCommand () ->
[15:10:45 INFO]: ItemPayCommand
[15:10:45 INFO]: [Man10Market] setupEconomy
[15:10:45 WARN]: [Man10Market] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.2-b107 which is not a depend, softdepend or loadbefore of this plugin.
[15:10:45 INFO]: [Man10Market] Economy setup
[15:10:45 INFO]: Vault完了
[15:10:45 INFO]: [Man10Market] Man10 Central Exchange loading....
[15:10:45 INFO]: init item bank
[15:10:45 INFO]: [Man10Market] Man10中央取引所オープンしました！ /MCE
[15:10:45 INFO]: load config done
[15:10:45 INFO]: config loaded -> register funcs
[15:10:45 INFO]: setup maps
[15:10:45 INFO]: MappRenderer created..
[15:10:45 INFO]: 3840546 registered.
[15:10:45 INFO]: [Man10Market] setupEconomy
[15:10:45 INFO]: [Man10Market] Economy setup
[15:10:45 INFO]: setup maps done !
[15:10:45 INFO]: [Man10Market] Config loaded  45.8.223.54 / MEC11
[15:10:45 ERROR]: Could not connect to MySQL server, error message: Public Key Retrieval is not allowed
[15:10:45 INFO]: failed to open MYSQL
[15:10:45 INFO]: [Man10Market] Unable to establish a MySQL connection.
[15:10:46 ERROR]: Could not connect to MySQL server, error message: Public Key Retrieval is not allowed
[15:10:46 INFO]: failed to open MYSQL
[15:10:46 WARN]: rs = null
[15:10:46 ERROR]: Error occurred while enabling Man10Market v1.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
        at red.man10.man10market.market.MarketChart.registerFuncs(MarketChart.kt:193) ~[?:?]
        at red.man10.man10market.MarketPlugin.onEnable(MarketPlugin.kt:732) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-185]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-185]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-185]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-185]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-185]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[15:10:46 INFO]: [Man10Market] Disabling Man10Market v1.0-SNAPSHOT

**Comment by Chiharu-Hagihara** [comment]
[15:10:43 INFO]: [Man10Market] Enabling Man10Market v1.0-SNAPSHOT
[15:10:43 INFO]: MarketCommand () ->
[15:10:43 INFO]: MarketCommand
[15:10:43 INFO]: [Man10Market] Config loaded  IP / USER
[15:10:44 ERROR]: Could not connect to MySQL server, error message: Public Key Retrieval is not allowed
[15:10:44 INFO]: failed to open MYSQL
[15:10:44 INFO]: [Man10Market] Unable to establish a MySQL connection.
[15:10:44 INFO]: [Man10Market] Config loaded   IP / USER
[15:10:45 ERROR]: Could not connect to MySQL server, error message: Public Key Retrieval is not allowed
[15:10:45 INFO]: failed to open MYSQL
[15:10:45 INFO]: [Man10Market] Unable to establish a MySQL connection.
[15:10:45 INFO]: [Man10Market] Config loaded   IP / USER
[15:10:45 ERROR]: Could not connect to MySQL server, error message: Public Key Retrieval is not allowed
[15:10:45 INFO]: failed to open MYSQL
[15:10:45 INFO]: [Man10Market] Unable to establish a MySQL connection.
[15:10:45 INFO]: BalanceCommand
[15:10:45 INFO]:  PayItemCommand () ->
[15:10:45 INFO]: ItemPayCommand
[15:10:45 INFO]: [Man10Market] setupEconomy
[15:10:45 WARN]: [Man10Market] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.2-b107 which is not a depend, softdepend or loadbefore of this plugin.
[15:10:45 INFO]: [Man10Market] Economy setup
[15:10:45 INFO]: Vault完了
[15:10:45 INFO]: [Man10Market] Man10 Central Exchange loading....
[15:10:45 INFO]: init item bank
[15:10:45 INFO]: [Man10Market] Man10中央取引所オープンしました！ /MCE
[15:10:45 INFO]: load config done
[15:10:45 INFO]: config loaded -> register funcs
[15:10:45 INFO]: setup maps
[15:10:45 INFO]: MappRenderer created..
[15:10:45 INFO]: 3840546 registered.
[15:10:45 INFO]: [Man10Market] setupEconomy
[15:10:45 INFO]: [Man10Market] Economy setup
[15:10:45 INFO]: setup maps done !
[15:10:45 INFO]: [Man10Market] Config loaded   IP / USER
[15:10:45 ERROR]: Could not connect to MySQL server, error message: Public Key Retrieval is not allowed
[15:10:45 INFO]: failed to open MYSQL
[15:10:45 INFO]: [Man10Market] Unable to establish a MySQL connection.
[15:10:46 ERROR]: Could not connect to MySQL server, error message: Public Key Retrieval is not allowed
[15:10:46 INFO]: failed to open MYSQL
[15:10:46 WARN]: rs = null
[15:10:46 ERROR]: Error occurred while enabling Man10Market v1.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
        at red.man10.man10market.market.MarketChart.registerFuncs(MarketChart.kt:193) ~[?:?]
        at red.man10.man10market.MarketPlugin.onEnable(MarketPlugin.kt:732) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-185]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-185]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-185]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-185]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-185]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-185]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[15:10:46 INFO]: [Man10Market] Disabling Man10Market v1.0-SNAPSHOT
